import numpy as np
import random
from variables import activation_functions


class Layer:
    """
    Layer of a neural network.
    """
    mutation_factor = 0.18
    weight_mutation_factor = 0.4
    bias_mutation_factor = 0.4

    def __init__(self, size, output_size, activation, weights=None, biases=None):
        """
        Initialize the Layer.

        Args:
            size (int): Number of inputs.
            output_size (int): Number of outputs(neurons).
            activation (str): Name of the Activation function.
            weights (np.ndarray): Weights (default=None).
            biases (np.ndarray): Biases (default=None).
        """
        random.seed(784)
        self.size = size
        self.output_size = output_size
        self.activation = activation
        self.activation_fx = activation_functions[activation]

        # If weights are not initialized, generate random weights.
        if weights is not None:
            self.weights = weights
        else:
            self.weights = np.random.randn(size, output_size)

        # If biases are not initialized, generate random biases.
        if biases is not None:
            self.biases = biases
        else:
            self.biases = np.random.randn(1, output_size)

    def feed_forward(self, data: np.ndarray) -> np.ndarray:
        """
        Forward data onto layers.

        :type data: np.ndarray
        :param data: Inputs to the layer.
        :return: Activations generated by the layer.
        """
        activations = self.activation_fx(
            np.dot(data, self.weights)
            + self.biases)
        return activations

    def mutate_layer(self) -> None:
        """
        In-place mutation of the layer.

        Works by randomly multiplying/dividing weight(s) by a random float in [0,1].

        :return: None
        """

        __N, __M = self.weights.shape
        for i in range(__M):
            decision = random.random() + Layer.mutation_factor
            if decision >= Layer.bias_mutation_factor:
                by_division = random.randint(0, 1)
                if by_division:
                    self.biases[0][i] /= random.random()
                else:
                    self.biases[0][i] *= random.random()
            for j in range(__N):
                decision = random.random() + Layer.mutation_factor
                if decision >= Layer.weight_mutation_factor:
                    by_division = random.randint(0, 1)
                    if by_division:
                        self.weights[j][i] /= random.random()
                    else:
                        self.weights[j][i] *= random.random()

    def __str__(self):
        return 'Layer({0}, {1}, activation={2})'.format(self.size, self.output_size, self.activation)
